Concurrency.Web/Controllers/XModelsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Concurrency.Definitions.CurrentUser;
using Concurrency.Definitions.XModels;
using Concurrency.Web.Models.XModels;
using Concurrency.Utils;

namespace Concurrency.Web.Controllers
{
    [Authorize]
    public class XModelsController : Controller
    {
        #region Constant

        const string MessageSystemEx = "System exeption";

        #endregion

        private readonly IXModelsService _xmodelsService;
        private readonly ICurrentUserService _currentUser;
        private readonly log4net.ILog _logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public XModelsController(
            IXModelsService xmodelsService,
            ICurrentUserService currentUser
            )
        {
            _xmodelsService = xmodelsService;
            _currentUser = currentUser;
        }

        public ActionResult Index()
        {
            ViewBag.CurrentUser = _currentUser.Get();

            return View();
        }

        [Route("xmodels/list")]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult List(int pageSize, int pageNumber, string orderBy = null)
        {   
            var totalCount = _xmodelsService.GetCount();
            var totalPages = Math.Ceiling((double)totalCount / pageSize);
            
            return Json(new ListViewModel
            {
                TotalCount = totalCount,
                totalPages = totalPages,
                Items = _xmodelsService.GetItemList(pageNumber, pageSize).ToArray()
            }, JsonRequestBehavior.AllowGet);
        }

        [Route("xmodels/details")]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Details(int? id)
        {
            var model = id.HasValue ? _xmodelsService.GetItem(id.Value)
                                    : new XModelDto();

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Route("xmodels/save")]
        public ActionResult Save(XModelDto model)
        {
            if (model == null)
                return HttpNotFound();

            try
            {  
                return Json(_xmodelsService.Save(model));
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    Success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                });
            }
        }

        [HttpPost]
        [Route("xmodels/delete")]
        public ActionResult Delete(int id, int version)
        {
            try
            {
                _xmodelsService.Delete(id, version);

                return Json(new
                {
                    success = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                });
            }
        }
    }
}

Concurrency.Web/Controllers/YModelsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Concurrency.Definitions.CurrentUser;
using Concurrency.Definitions.YModels;
using Concurrency.Web.Models.YModels;
using Concurrency.Utils;

namespace Concurrency.Web.Controllers
{
    [Authorize]
    public class YModelsController : Controller
    {
        #region Constant

        const string MessageSystemEx = "System exeption";

        #endregion

        private readonly IYModelsService _yModelsService;
        private readonly ICurrentUserService _currentUser;
        private readonly IBlockService _blockService;

        private readonly log4net.ILog _logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        public YModelsController(
            IYModelsService yModelsService,
            ICurrentUserService currentUser,
            IBlockService blockService
            )
        {
            _yModelsService = yModelsService;
            _currentUser = currentUser;
            _blockService = blockService;
        }

        public ActionResult Index()
        {
            ViewBag.CurrentUser = _currentUser.Get();

            return View();
        }

        [Route("ymodels/list")]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult List(int pageSize, int pageNumber, string orderBy = "")
        {
            var totalCount = _yModelsService.GetCount();
            var totalPages = Math.Ceiling((double)totalCount / pageSize);
           
            return Json(new ListViewModel
            {
                TotalCount = totalCount,
                totalPages =  totalPages,
                Items = _yModelsService.GetItemList(pageNumber, pageSize).ToArray()
            }, JsonRequestBehavior.AllowGet);
        }

        [Route("ymodels/details")]
        [OutputCache(NoStore = true, Duration = 0)]
        public ActionResult Details(int? id)
        {
            try
            {
                var model = id.HasValue
                    ? _yModelsService.GetItem(id.Value)
                    : new YModelDto();

                var currentUser = _currentUser.Get();

                return Json(new DetailsViewModel
                {
                    Success = true,
                    Item = model,
                    CurrentUserId = currentUser.Id
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    Success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Route("ymodels/save")]
        public ActionResult Save(YModelDto model)
        {   
            if (model == null)
                return HttpNotFound();
            
            try
            {
                _yModelsService.Save(model);

                return Json(new
                {
                    Success = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    Success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                });
            }
        }

        [HttpPost]
        [Route("ymodels/delete")]
        public ActionResult Delete(int id)
        {
            try
            {
                _yModelsService.Delete(id);

                return Json(new
                {
                    Success = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    Success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                });
            }
        }

        [HttpPost]
        [Route("ymodels/unblock")]
        public ActionResult Unblock(int id)
        {
            try
            {
                _blockService.UnBlock(id);

                return Json(new
                {
                    Success = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    Success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                });
            }
        }

        [HttpPost]
        [Route("ymodels/checkblock")]
        public ActionResult CheckBlock(int id)
        {
            try
            {
                _blockService.CheckBlock(id);

                return Json(new
                {
                    Success = true
                });
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);

                return Json(new
                {
                    Success = false,
                    Message = ex is CustomExeption ? ex.Message : MessageSystemEx
                });
            }
        }
    }
}

Concurrency.Web/Views/Shared/_Layout.cshtml
@using Concurrency.Definitions.CurrentUser

@{
    var currentUser = ViewBag.CurrentUser as CurrentUser;
}

<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns= "http://www.w3.org/1999/xhtml" data-ng-app="concurrencyApp">
<head>
    <meta charset="utf-8" />
    <meta name="google" content="notranslate">
    <meta http-equiv="Content-Language" content="en">

    <title>Modules</title>
    
    <base href="/" />
    <script>
        // Must be first. IE10 mobile viewport fix
        if ("-ms-user-select" in document.documentElement.style && navigator.userAgent.match(/IEMobile\/10\.0/)) {
            var msViewportStyle = document.createElement("style");
            var mq = "@@-ms-viewport{width:auto!important}";
            msViewportStyle.appendChild(document.createTextNode(mq));
            document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
        }
    </script>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angularjs")
    @Scripts.Render("~/bundles/common")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                      
            </div>
            <div class="navbar-collapse collapse">
                <div class="row" id="nav-panel">
                    <div class="col-md-8">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("X models", "Index", "XModels")</li>
                            <li>@Html.ActionLink("Y models", "Index", "YModels")</li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <ul class="nav navbar-nav">
                            <li><a>@(currentUser == null ? string.Empty : currentUser.Logname)</a></li>
                            <li><a href="/account/logoff">Log out</a></li>
                        </ul>
                    </div>
                </div>                
            </div>            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
    
</body>
</html>